from __future__ import annotations

from time import perf_counter
from typing import Any

import pandas as pd

from beyond_click_sim.data.canonical import CanonicalDataset
from beyond_click_sim.evaluation import evaluate_policy_recommendations
from beyond_click_sim.tasks.base import (
    DatasetFilter,
    ItemFeatureBuilder,
    Splitter,
    Task,
    TaskBuilder,
    TaskSchema,
)
from beyond_click_sim.tasks.item_enrichment import item_enrichment_manifest
from beyond_click_sim.tasks.policies import Policy
from beyond_click_sim.tasks.samplers import PostSplitUserSampler

POLICY_EVAL_KS = (1, 3, 5, 10)


class PolicyRankingTaskBuilder(TaskBuilder):
    """Build a policy-ranking task for Q3 evaluation.

    Train contains all observed interactions for scorer fitting. Test contains
    recommendation rows generated by each policy for each evaluation user, with
    real outcome targets derived from held-out test interactions.

    Val is always empty — no threshold selection is needed for Q3.

    The test DataFrame has one row per (user, policy, recommended_item). Beyond
    the standard scorer-visible columns (user_id, item_id, features,
    history_context_columns), each test row also carries:

    - ``policy``:   string name of the recommender policy
    - ``rank``:     integer rank assigned by the policy (1 = most recommended)

    These extra columns are not part of TaskSchema (they are not scorer inputs);
    they are used by the runner to aggregate policy-level utilities.

    ``target`` is 1 if the recommended (user_id, item_id) pair appears in the
    user's held-out test interactions with a positive ``target_source_column``
    value, and 0 otherwise.
    """

    def __init__(
        self,
        name: str,
        dataset_filter: DatasetFilter,
        splitter: Splitter,
        policies: list[Policy],
        *,
        target_source_column: str = "target_interact",
        target_column: str = "target",
        user_column: str = "user_id",
        item_column: str = "item_id",
        history_context_columns: tuple[str, ...] = (),
        eval_sampler: PostSplitUserSampler | None = None,
        item_feature_builder: ItemFeatureBuilder | None = None,
    ) -> None:
        super().__init__(
            name=name,
            target_source_column=target_source_column,
            dataset_filter=dataset_filter,
            splitter=splitter,
            sampler=None,
            target_column=target_column,
            user_column=user_column,
            item_column=item_column,
            sampled_column=None,
            candidate_group_column=None,
            history_context_columns=history_context_columns,
            item_feature_builder=item_feature_builder,
        )
        if not policies:
            raise ValueError("policies must be non-empty.")
        if self.dataset_filter is None:
            raise ValueError("PolicyRankingTaskBuilder requires dataset_filter.")
        if self.splitter is None:
            raise ValueError("PolicyRankingTaskBuilder requires splitter.")
        self.policies = list(policies)
        self.eval_sampler = eval_sampler
        if (
            self.eval_sampler is not None
            and getattr(self.eval_sampler, "max_rows_per_user", None) is not None
        ):
            raise ValueError(
                "PolicyRankingTaskBuilder cannot use a row-capped eval sampler: "
                "policy-ranking target lookup needs all held-out rows for each "
                "selected evaluation user."
            )
        self._validate_history_context_columns()

    def build(self, dataset: CanonicalDataset) -> Task:
        canonical_manifest = dataset.load_manifest()
        users = dataset.load_users()
        items = dataset.load_items()
        interactions = dataset.load_interactions()
        task_item_enrichment = item_enrichment_manifest(canonical_manifest, items)

        self._require_columns(interactions, [self.user_column, self.item_column])
        self._require_columns(
            interactions,
            [self.target_source_column, *self.history_context_columns],
        )
        self._require_columns(users, [self.user_column])
        self._require_columns(items, [self.item_column])

        users, items, interactions = self.dataset_filter.filter(
            users=users,
            items=items,
            interactions=interactions,
        )
        split = self.splitter.split(interactions)

        # Cap evaluation users via optional post-split sampler.
        test_interactions, test_eval_summary = self._sample_eval_rows(
            split.test,
            train=split.train,
        )

        # Determine which users to evaluate and build recommendation rows.
        test_users = (
            users[users[self.user_column].isin(
                test_interactions[self.user_column].unique()
            )].copy()
        )
        # Compute real targets: 1 if (user, item) in test interactions with positive label.
        test_targets: dict[tuple[Any, Any], Any] = {}
        for _, row in test_interactions.iterrows():
            key = (row[self.user_column], row[self.item_column])
            test_targets[key] = row[self.target_source_column]

        rec_frames: list[pd.DataFrame] = []
        policy_metrics: list[dict[str, object]] = []
        for policy in self.policies:
            t0 = perf_counter()
            policy.fit(
                split.train,
                items=items,
                user_column=self.user_column,
                item_column=self.item_column,
            )
            recs = policy.recommend(
                test_users,
                train_interactions=split.train,
                items=items,
                user_column=self.user_column,
                item_column=self.item_column,
            )
            recs = recs.copy()
            recs[self.target_column] = [
                test_targets.get(
                    (row[self.user_column], row[self.item_column]),
                    0,
                )
                for _, row in recs.iterrows()
            ]
            policy_metric = evaluate_policy_recommendations(
                recs,
                targets=recs[self.target_column],
                user_column=self.user_column,
                policy_name=policy.name,
                k=policy.k,
                ks=POLICY_EVAL_KS,
                fit_recommend_seconds=perf_counter() - t0,
            )
            policy_metrics.append(policy_metric)
            k_for_metrics = policy.k if policy.k in POLICY_EVAL_KS else max(POLICY_EVAL_KS)
            ndcg_at_k_key = f"ndcg@{k_for_metrics}"
            hr_at_k_key = f"hit_rate@{k_for_metrics}"
            ranking = policy_metric["ranking"]
            if not isinstance(ranking, dict):
                raise TypeError("policy_metric['ranking'] must be a dict.")
            macro_by_user = ranking.get("macro_by_user_group_mean")
            if not isinstance(macro_by_user, dict):
                raise TypeError(
                    "policy_metric['ranking']['macro_by_user_group_mean'] must be a dict."
                )
            hr_at_k = float(macro_by_user.get(hr_at_k_key, 0.0))
            ndcg_at_k = float(macro_by_user[ndcg_at_k_key])
            print(
                f"Policy {policy.name}: "
                f"mean_hit_rate={policy_metric['mean_hit_rate']:.4f} "
                f"HR@{k_for_metrics}={hr_at_k:.4f} "
                f"NDCG@{k_for_metrics}={ndcg_at_k:.4f} "
                f"users={policy_metric['n_users']} "
                f"recs={policy_metric['n_recommendations']} "
                f"({policy_metric.get('fit_recommend_seconds', 0.0):.3f}s)",
                flush=True,
            )
            rec_frames.append(recs)

        all_recs = pd.concat(rec_frames, ignore_index=True) if rec_frames else pd.DataFrame(
            columns=[
                self.user_column,
                self.item_column,
                "policy",
                "rank",
                self.target_column,
            ]
        )

        # Mask history context columns to NA for test rows (no leakage).
        for col in self.history_context_columns:
            all_recs[col] = pd.NA

        # Enrich items with train-only features.
        items, item_feature_manifest = self._enrich_items_from_train(
            items=items,
            train_interactions=split.train,
        )

        user_features = self._prefixed_features(users, self.user_column, "user")
        item_features = self._prefixed_features(items, self.item_column, "item")
        feature_columns = self._feature_columns(
            user_features,
            item_features,
            user_column=self.user_column,
            item_column=self.item_column,
        )

        # Build test: join features onto recommendation rows.
        test_task_columns = self._task_columns(feature_columns) + ["policy", "rank"]
        test = self._with_features(
            rows=all_recs,
            user_features=user_features,
            item_features=item_features,
            columns=test_task_columns,
            user_column=self.user_column,
            item_column=self.item_column,
        )

        # Build train: observed interactions with features (same as regression builder).
        train_rows = self._target_rows(split.train)
        train_task_columns = self._task_columns(feature_columns)
        train = self._with_features(
            rows=train_rows,
            user_features=user_features,
            item_features=item_features,
            columns=train_task_columns,
            user_column=self.user_column,
            item_column=self.item_column,
        )

        # Val is always empty.
        val = pd.DataFrame(columns=train.columns)

        schema = TaskSchema(
            target_column=self.target_column,
            feature_columns=feature_columns,
            id_columns=(self.user_column, self.item_column),
            candidate_group_column=None,
            sampled_column=None,
            history_context_columns=self.history_context_columns,
        )

        return Task(
            name=self.name,
            train=train,
            val=val,
            test=test,
            schema=schema,
            manifest={
                "protocol": "policy_ranking",
                "dataset": dataset.name,
                "dataset_version": dataset.version,
                "target_source_column": self.target_source_column,
                "target_column": self.target_column,
                "feature_columns": list(feature_columns),
                "history_context_columns": list(self.history_context_columns),
                "item_enrichment": task_item_enrichment,
                "item_feature_builder": item_feature_manifest,
                "policies": [
                    {
                        "class": policy.__class__.__name__,
                        "name": policy.name,
                        "k": policy.k,
                        "seed": policy.seed,
                    }
                    for policy in self.policies
                ],
                "filter": self._component_manifest(self.dataset_filter),
                "splitter": self._component_manifest(self.splitter),
                "sampler": None,
                "eval_sampler": (
                    None
                    if self.eval_sampler is None
                    else self._component_manifest(self.eval_sampler)
                ),
                "eval_user_selection": {
                    "kind": "post_split",
                    "test": test_eval_summary,
                },
                "policy_recommendation_metrics": {
                    "protocol": "held_out_recommendation_eval",
                    "target_source_column": self.target_source_column,
                    "ks": list(POLICY_EVAL_KS),
                    "ranking_score": "negative_rank",
                    "aggregation_headline": "macro_by_user_group_mean",
                    "policies": policy_metrics,
                },
                "rows": {
                    "train": int(len(train)),
                    "val": 0,
                    "test": int(len(test)),
                },
                "users": {
                    "filtered": int(interactions[self.user_column].nunique()),
                    "train": int(split.train[self.user_column].nunique()),
                    "test": int(test_interactions[self.user_column].nunique()),
                },
                "items": int(items[self.item_column].nunique()),
            },
        )

    def _target_rows(self, interactions: pd.DataFrame) -> pd.DataFrame:
        rows = interactions[
            [self.user_column, self.item_column, *self.history_context_columns]
        ].copy()
        rows[self.target_column] = interactions[self.target_source_column]
        return rows

    def _sample_eval_rows(
        self,
        rows: pd.DataFrame,
        *,
        train: pd.DataFrame,
    ) -> tuple[pd.DataFrame, dict[str, int | None]]:
        if self.eval_sampler is not None:
            return self.eval_sampler.sample(rows, train=train)
        if rows.empty:
            return rows.copy(), {
                "eligible_users": 0,
                "selected_users": 0,
                "rows_before": 0,
                "rows_after": 0,
            }
        return rows.copy(), {
            "eligible_users": int(rows[self.user_column].nunique()),
            "selected_users": int(rows[self.user_column].nunique()),
            "rows_before": int(len(rows)),
            "rows_after": int(len(rows)),
        }

    def _task_columns(self, feature_columns: tuple[str, ...]) -> list[str]:
        return [
            self.user_column,
            self.item_column,
            *feature_columns,
            *self.history_context_columns,
            self.target_column,
        ]

    def _validate_history_context_columns(self) -> None:
        reserved = {self.user_column, self.item_column, self.target_column}
        overlaps = [
            col for col in self.history_context_columns if col in reserved
        ]
        if overlaps:
            raise ValueError(
                "history_context_columns cannot include task control columns: "
                f"{overlaps}"
            )
