# litellm_config.yaml
model_list:
  - model_name: Qwen/Qwen3.6-35B-A3B
    litellm_params:
      model: openai/Qwen/Qwen3.6-35B-A3B
      api_base: http://localhost:8000/v1
      api_key: "not-needed"
  - model_name: Qwen/Qwen3.6-35B-A3B
    litellm_params:
      model: openai/Qwen/Qwen3.6-35B-A3B
      api_base: http://localhost:8001/v1
      api_key: "not-needed"
  - model_name: Qwen/Qwen3.6-35B-A3B
    litellm_params:
      model: openai/Qwen/Qwen3.6-35B-A3B
      api_base: http://localhost:8002/v1
      api_key: "not-needed"
  - model_name: Qwen/Qwen3.6-35B-A3B
    litellm_params:
      model: openai/Qwen/Qwen3.6-35B-A3B
      api_base: http://localhost:8003/v1
      api_key: "not-needed"

router_settings:
  routing_strategy: least-busy  # or "usage-based-routing", "latency-based-routing"
